dubbo:
  scan:
    base-packages: com.gupaoedu.springcloud.seata.springcloudseatarest
  cloud:
    subscribed-services: spring-cloud-seata-order,spring-cloud-seata-repo
spring:
  application:
    name: spring-cloud-seata-rest
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.74.132:8848
server:
  port: 9004